module.exports = [
    {
        1: "aa",
        2: "ab",
        3: "ac",
        4: "ad",
        5: "ae",
        6: "af",
        7: "ag",
        8: "ah",
        9: "ai",
        10: "aj",
        11: "ak",
        12: "al",
        13: "am",
        14: "an",
        15: "ao",
        16: "ap",
    },
];
